name: Syria News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "7,22,37,52 * * * *"

permissions:
  contents: write

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Syria news bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
        run: python syria_news_bot_telegram_facebook_v12.py

      - name: Save published news and app news
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f published_telegram_news.json ]; then
            git add published_telegram_news.json
          fi

          if [ -f news.json ]; then
            git add news.json
          fi

          if ! git diff --cached --quiet; then
            git commit -m "Update published and app news"
            git pull --rebase origin main
            git push origin main
          fi
