name: Telegram News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0,15 * * * *"

permissions:
  contents: write

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run news bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: python 11Top_News.py

      - name: Save published news list
        run: |
          if [ -f published_top_news.txt ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add published_top_news.txt
            git diff --cached --quiet || git commit -m "Update published news"
            git push
          fi
